name: i_have_lived
description: A new Flutter project.

publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_mobile_ads: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"